---
spring:
  config:
    activate:
      on-profile: dev

application:
  client-origin-url: http://localhost:3000

server:
  error:
    whitelabel:
      enabled: false
  port: 8080

  web:
    resources:
      add-mappings: false

# OAuth2 configuration commented out - not required for dummy endpoints
okta:
  oauth2:
    issuer: https://dev-goqh5m0ncp572g5s.us.auth0.com/
    audience: https://api.authdemo.com
...
